/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNIFrame */

#ifndef _Included_JNIFrame
#define _Included_JNIFrame
#ifdef __cplusplus
extern "C" {
#endif
#undef JNIFrame_FOCUS_TRAVERSABLE_UNKNOWN
#define JNIFrame_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef JNIFrame_FOCUS_TRAVERSABLE_DEFAULT
#define JNIFrame_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef JNIFrame_FOCUS_TRAVERSABLE_SET
#define JNIFrame_FOCUS_TRAVERSABLE_SET 2L
/* Inaccessible static: focusTraversalKeyPropertyNames */
/* Inaccessible static: LOCK */
/* Inaccessible static: dbg */
/* Inaccessible static: isInc */
/* Inaccessible static: incRate */
#undef JNIFrame_TOP_ALIGNMENT
#define JNIFrame_TOP_ALIGNMENT 0.0f
#undef JNIFrame_CENTER_ALIGNMENT
#define JNIFrame_CENTER_ALIGNMENT 0.5f
#undef JNIFrame_BOTTOM_ALIGNMENT
#define JNIFrame_BOTTOM_ALIGNMENT 1.0f
#undef JNIFrame_LEFT_ALIGNMENT
#define JNIFrame_LEFT_ALIGNMENT 0.0f
#undef JNIFrame_RIGHT_ALIGNMENT
#define JNIFrame_RIGHT_ALIGNMENT 1.0f
#undef JNIFrame_serialVersionUID
#define JNIFrame_serialVersionUID -7644114512714619750i64
/* Inaccessible static: metrics */
/* Inaccessible static: class_00024java_00024awt_00024Component */
/* Inaccessible static: class_00024java_00024awt_00024event_00024ComponentListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024FocusListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024HierarchyListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024HierarchyBoundsListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024KeyListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024MouseListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024MouseMotionListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024MouseWheelListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024InputMethodListener */
/* Inaccessible static: class_00024java_00024beans_00024PropertyChangeListener */
#undef JNIFrame_serialVersionUID
#define JNIFrame_serialVersionUID 4613797578919906343i64
/* Inaccessible static: dbg */
#undef JNIFrame_INCLUDE_SELF
#define JNIFrame_INCLUDE_SELF 1L
#undef JNIFrame_SEARCH_HEAVYWEIGHTS
#define JNIFrame_SEARCH_HEAVYWEIGHTS 1L
/* Inaccessible static: class_00024java_00024awt_00024Container */
/* Inaccessible static: class_00024java_00024awt_00024event_00024ContainerListener */
#undef JNIFrame_OPENED
#define JNIFrame_OPENED 1L
/* Inaccessible static: nameCounter */
#undef JNIFrame_serialVersionUID
#define JNIFrame_serialVersionUID 4497834738069338734i64
/* Inaccessible static: dbg */
/* Inaccessible static: class_00024java_00024awt_00024Window */
/* Inaccessible static: class_00024java_00024awt_00024event_00024WindowListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024WindowFocusListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024WindowStateListener */
#undef JNIFrame_DEFAULT_CURSOR
#define JNIFrame_DEFAULT_CURSOR 0L
#undef JNIFrame_CROSSHAIR_CURSOR
#define JNIFrame_CROSSHAIR_CURSOR 1L
#undef JNIFrame_TEXT_CURSOR
#define JNIFrame_TEXT_CURSOR 2L
#undef JNIFrame_WAIT_CURSOR
#define JNIFrame_WAIT_CURSOR 3L
#undef JNIFrame_SW_RESIZE_CURSOR
#define JNIFrame_SW_RESIZE_CURSOR 4L
#undef JNIFrame_SE_RESIZE_CURSOR
#define JNIFrame_SE_RESIZE_CURSOR 5L
#undef JNIFrame_NW_RESIZE_CURSOR
#define JNIFrame_NW_RESIZE_CURSOR 6L
#undef JNIFrame_NE_RESIZE_CURSOR
#define JNIFrame_NE_RESIZE_CURSOR 7L
#undef JNIFrame_N_RESIZE_CURSOR
#define JNIFrame_N_RESIZE_CURSOR 8L
#undef JNIFrame_S_RESIZE_CURSOR
#define JNIFrame_S_RESIZE_CURSOR 9L
#undef JNIFrame_W_RESIZE_CURSOR
#define JNIFrame_W_RESIZE_CURSOR 10L
#undef JNIFrame_E_RESIZE_CURSOR
#define JNIFrame_E_RESIZE_CURSOR 11L
#undef JNIFrame_HAND_CURSOR
#define JNIFrame_HAND_CURSOR 12L
#undef JNIFrame_MOVE_CURSOR
#define JNIFrame_MOVE_CURSOR 13L
#undef JNIFrame_NORMAL
#define JNIFrame_NORMAL 0L
#undef JNIFrame_ICONIFIED
#define JNIFrame_ICONIFIED 1L
#undef JNIFrame_MAXIMIZED_HORIZ
#define JNIFrame_MAXIMIZED_HORIZ 2L
#undef JNIFrame_MAXIMIZED_VERT
#define JNIFrame_MAXIMIZED_VERT 4L
#undef JNIFrame_MAXIMIZED_BOTH
#define JNIFrame_MAXIMIZED_BOTH 6L
/* Inaccessible static: nameCounter */
#undef JNIFrame_serialVersionUID
#define JNIFrame_serialVersionUID 2673458971256075116i64
/* Inaccessible static: class_00024java_00024awt_00024Frame */
#undef JNIFrame_EXIT_ON_CLOSE
#define JNIFrame_EXIT_ON_CLOSE 3L
/* Inaccessible static: defaultLookAndFeelDecoratedKey */
/*
 * Class:     JNIFrame
 * Method:    getHwnd
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_JNIFrame_getHwnd
  (JNIEnv *, jclass, jstring);

/*
 * Class:     JNIFrame
 * Method:    toFront
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_JNIFrame_toFront
  (JNIEnv *, jclass, jint);

/*
 * Class:     JNIFrame
 * Method:    flash
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_JNIFrame_flash
  (JNIEnv *, jclass, jint);

/*
 * Class:     JNIFrame
 * Method:    noSizeChange
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_JNIFrame_noSizeChange
  (JNIEnv *, jclass, jint);

/*
 * Class:     JNIFrame
 * Method:    restore
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_JNIFrame_restore
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
